# Machine Learning - Open CV Project - Converting image to vector.

In [1]:
import cv2
import numpy as np
import pandas as pd
import os
import warnings 
warnings.filterwarnings('ignore')

In [2]:
os.getcwd()

'C:\\Users\\Gogula Vinay'

In [3]:
os.chdir(r'C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Animal Assignment\train')

In [4]:
os.getcwd()

'C:\\Users\\Gogula Vinay\\Desktop\\Innomatics labs\\Data Science\\Machine Learning\\Animal Assignment\\train'

In [5]:
file_names = os.listdir()

In [6]:
catlist= []
doglist= []
for i in file_names:
    if 'cat' in i:catlist.append(i)
    else:doglist.append(i)

In [7]:
#dynamically creating folders
folder_names = ['cat','dog']
for i in folder_names:
    os.mkdir(r'C:\\Users\\Gogula Vinay\\Desktop\\Innomatics labs\\Data Science\\Machine Learning\\Animal Assignment\\'+i)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\\\Users\\\\Gogula Vinay\\\\Desktop\\\\Innomatics labs\\\\Data Science\\\\Machine Learning\\\\Animal Assignment\\\\cat'

In [50]:
url=r"C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Animal Assignment\train"
cats=[]
for i in catlist:
    cats.append(url+'\\'+i)

In [51]:
url=r"C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Animal Assignment\train"
dogs=[]
for i in doglist:
    dogs.append(url+'\\'+i)

In [82]:
c=0
for i in cats:
    c=c+1
    image=cv2.imread(i,0)
    cv2.imwrite(r"C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Animal Assignment\cat\{}.jpg".format(c),image)

In [83]:
c=0
for i in dogs:
    c=c+1
    image=cv2.imread(i,0)
    cv2.imwrite(r"C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Animal Assignment\dog\{}{}.jpg".format('dog',c),image)

In [ ]:
# Converting cat images into Vectors

In [2]:
url=r"C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Animal Assignment\cat"
x1=[]
for i in range(1,12500):
    x1.append(url+'\\'+str(i)+'.jpg')

In [3]:
l1=[]
for i in x1:
    image=cv2.imread(i)
    image=cv2.resize(image,(100,100))
    l1.append(image.flatten().tolist())

In [4]:
catdf=pd.DataFrame(l1)
catdf['label']='cat'
catdf

,0,1,2,3,4,5,6,7,8,9,...,29991,29992,29993,29994,29995,29996,29997,29998,29999,label
0,168,168,168,174,174,174,177,177,177,181,...,2,2,2,2,2,2,2,2,2,cat
1,43,43,43,44,44,44,43,43,43,42,...,89,89,89,20,20,20,36,36,36,cat
2,39,39,39,25,25,25,43,43,43,50,...,169,169,169,171,171,171,153,153,153,cat
3,221,221,221,224,224,224,222,222,222,228,...,217,217,217,211,211,211,213,213,213,cat
4,115,115,115,119,119,119,122,122,122,92,...,91,91,91,94,94,94,81,81,81,cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12494,204,204,204,222,222,222,243,243,243,253,...,156,156,156,176,176,176,190,190,190,cat
12495,24,24,24,22,22,22,21,21,21,21,...,79,79,79,71,71,71,74,74,74,cat
12496,101,101,101,96,96,96,92,92,92,92,...,100,100,100,103,103,103,99,99,99,cat
12497,96,96,96,98,98,98,97,97,97,97,...,254,254,254,254,254,254,254,254,254,cat
12498,57,57,57,53,53,53,48,48,48,107,...,221,221,221,218,218,218,216,216,216,cat

In [5]:
# Converting dog images into Vectors

In [6]:
url=r"C:\Users\Gogula Vinay\Desktop\Innomatics labs\Data Science\Machine Learning\Animal Assignment\dog\dog"
y1=[]
for i in range(1,12500):
    y1.append(url+str(i)+'.jpg')

In [7]:
l1=[]
for i in y1:
    image=cv2.imread(i)
    image=cv2.resize(image,(100,100))
    l1.append(image.flatten().tolist())

In [8]:
dogdf=pd.DataFrame(l1)
dogdf['label']='dog'
dogdf

,0,1,2,3,4,5,6,7,8,9,...,29991,29992,29993,29994,29995,29996,29997,29998,29999,label
0,119,119,119,109,109,109,153,153,153,161,...,68,68,68,87,87,87,75,75,75,dog
1,146,146,146,119,119,119,124,124,124,132,...,241,241,241,239,239,239,237,237,237,dog
2,118,118,118,109,109,109,93,93,93,98,...,92,92,92,94,94,94,94,94,94,dog
3,185,185,185,184,184,184,186,186,186,183,...,59,59,59,69,69,69,71,71,71,dog
4,16,16,16,7,7,7,7,7,7,7,...,123,123,123,116,116,116,116,116,116,dog
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12494,122,122,122,128,128,128,124,124,124,125,...,26,26,26,21,21,21,17,17,17,dog
12495,140,140,140,143,143,143,142,142,142,145,...,168,168,168,168,168,168,169,169,169,dog
12496,117,117,117,78,78,78,103,103,103,83,...,93,93,93,94,94,94,75,75,75,dog
12497,42,42,42,35,35,35,47,47,47,58,...,128,128,128,114,114,114,166,166,166,dog
12498,254,254,254,251,251,251,245,245,245,234,...,116,116,116,114,114,114,121,121,121,dog

In [9]:
finaldf=pd.concat([catdf,dogdf])

In [10]:
finaldf

,0,1,2,3,4,5,6,7,8,9,...,29991,29992,29993,29994,29995,29996,29997,29998,29999,label
0,168,168,168,174,174,174,177,177,177,181,...,2,2,2,2,2,2,2,2,2,cat
1,43,43,43,44,44,44,43,43,43,42,...,89,89,89,20,20,20,36,36,36,cat
2,39,39,39,25,25,25,43,43,43,50,...,169,169,169,171,171,171,153,153,153,cat
3,221,221,221,224,224,224,222,222,222,228,...,217,217,217,211,211,211,213,213,213,cat
4,115,115,115,119,119,119,122,122,122,92,...,91,91,91,94,94,94,81,81,81,cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12494,122,122,122,128,128,128,124,124,124,125,...,26,26,26,21,21,21,17,17,17,dog
12495,140,140,140,143,143,143,142,142,142,145,...,168,168,168,168,168,168,169,169,169,dog
12496,117,117,117,78,78,78,103,103,103,83,...,93,93,93,94,94,94,75,75,75,dog
12497,42,42,42,35,35,35,47,47,47,58,...,128,128,128,114,114,114,166,166,166,dog
12498,254,254,254,251,251,251,245,245,245,234,...,116,116,116,114,114,114,121,121,121,dog